apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx_app
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
kubectl apply -f pod-nginx.yaml
kubectl get pod pod-nginx -o yaml | grep image
kubectl get pod pod-nginx -o jsonpath='{.metadata.labels}'
kubectl get pods
